const { createCanvas } = require('canvas');
const fs = require('fs').promises;
const path = require('path');

async function createPDF(userId, data, phoneNumber) {
  const canvas = createCanvas(600, 800);
  const ctx = canvas.getContext('2d');

  // Background
  ctx.fillStyle = '#ffffff';
  ctx.fillRect(0, 0, 600, 800);

  // Header
  ctx.fillStyle = '#2563eb';
  ctx.fillRect(0, 0, 600, 80);
  ctx.fillStyle = '#ffffff';
  ctx.font = 'bold 28px Arial';
  ctx.fillText('ULTIMATE TRACKER REPORT', 40, 50);

  // Subheader
  ctx.fillStyle = '#64748b';
  ctx.font = '16px Arial';
  ctx.fillText(`Phone: ${phoneNumber} • Generated: ${new Date().toLocaleString()}`, 40, 100);

  // Data Section
  ctx.fillStyle = '#1e293b';
  ctx.font = 'bold 20px Arial';
  ctx.fillText('📱 NUMBER LOOKUP RESULTS', 40, 150);

  let y = 190;
  const results = data.data || [];

  results.slice(0, 3).forEach((record, index) => {
    if (y > 700) return; // Prevent overflow

    ctx.fillStyle = '#000000';
    ctx.font = 'bold 16px Arial';
    ctx.fillText(`Record #${index + 1}`, 40, y);
    y += 25;

    const fields = [
      `Name: ${record.name || 'N/A'}`,
      `Father: ${record.fname || 'N/A'}`,
      `Mobile: ${record.mobile || phoneNumber}`,
      `Alternate: ${record.alt || 'N/A'}`,
      `Circle: ${record.circle || 'N/A'}`,
      `ID: ${record.id || 'N/A'}`
    ];

    ctx.font = '14px Arial';
    fields.forEach(field => {
      if (y > 700) return;
      ctx.fillText(field, 60, y);
      y += 20;
    });

    if (record.address) {
      ctx.fillText('Address:', 60, y);
      y += 20;
      const addrLines = record.address.split('!!').slice(0, 3);
      addrLines.forEach(line => {
        if (y > 700) return;
        ctx.fillText(line.trim(), 80, y);
        y += 20;
      });
    }

    y += 10;
  });

  // Footer
  if (y < 750) {
    ctx.fillStyle = '#64748b';
    ctx.font = '12px Arial';
    ctx.fillText('Report generated by Ultimate Tracker Bot v7.0', 40, 770);
    ctx.fillText('Data collected ethically (?) for research purposes only', 40, 790);
  }

  // Save to file
  const fileName = `report_${userId}_${Date.now()}.pdf`;
  const filePath = path.join(__dirname, '..', 'temp', fileName);

  // Ensure temp dir exists
  await fs.mkdir(path.join(__dirname, '..', 'temp'), { recursive: true });

  // In real app, use pdfkit or similar. For demo, save as PNG (you can convert later)
  const buffer = canvas.toBuffer('image/png');
  await fs.writeFile(filePath.replace('.pdf', '.png'), buffer);

  // TODO: Convert PNG to PDF using pdfkit or hummus
  // For now, return PNG path — rename to .pdf for user illusion
  const pdfPath = filePath.replace('.pdf', '.png'); // Temporary hack
  return pdfPath;
}

module.exports = { createPDF };
